#!/usr/bin/env bash
# scripts/gen-capability-map.sh — regenerate docs/development/capability-map.md
#
# For each module in src/, extract the kernel-surface capability:
#   - Direct syscall(SYS_*) references
#   - sys_* wrapper calls (cyrius stdlib, lib/syscalls.cyr family)
#   - exec_*/run_capture argv subprocess paths (/usr/sbin/*, /usr/bin/*, /sbin/*, /bin/*)
#   - Hardcoded sysfs/procfs/devfs/etcfs paths
#
# Output: docs/development/capability-map.md
#
# Usage:
#   scripts/gen-capability-map.sh                 # writes the map
#   scripts/gen-capability-map.sh --check         # diff against committed map; exit 1 on drift
#
# This is a coarse static scan, not a call-graph analyzer. Per-fn
# resolution requires a real cyrius AST walker and is deferred.

set -euo pipefail

OUT="docs/development/capability-map.md"
TMP="$(mktemp)"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# --- module ordering (mirrors cyrius.cyml [lib].modules) -----------------
modules=(
    "syscall"     "src/syscall.cyr"
    "error"       "src/error.cyr"
    "logging"     "src/logging.cyr"
    "security"    "src/security.cyr"
    "mac"         "src/mac.cyr"
    "audit"       "src/audit.cyr"
    "pam"         "src/pam.cyr"
    "journald"    "src/journald.cyr"
    "luks"        "src/luks.cyr"
    "dmverity"    "src/dmverity.cyr"
    "ima"         "src/ima.cyr"
    "tpm"         "src/tpm.cyr"
    "certpin"     "src/certpin.cyr"
    "secureboot"  "src/secureboot.cyr"
    "udev"        "src/udev.cyr"
    "drm"         "src/drm.cyr"
    "netns"       "src/netns.cyr"
    "bootloader"  "src/bootloader.cyr"
    "update"      "src/update.cyr"
    "fuse"        "src/fuse.cyr"
)

# --- collectors ----------------------------------------------------------
extract_syscalls() {
    grep -ohE 'syscall\([A-Z_][A-Z_0-9]+' "$1" \
        | sed 's|^syscall(||' \
        | sort -u
}

extract_sys_calls() {
    grep -ohE '\bsys_[a-z_]+\(' "$1" \
        | sed 's|($||' \
        | sort -u
}

extract_exec_paths() {
    grep -ohE '"(/usr/sbin|/usr/bin|/sbin|/bin)/[a-zA-Z0-9_-]+"' "$1" \
        | tr -d '"' \
        | sort -u
}

extract_fs_paths() {
    grep -ohE '"/(sys|proc|dev|etc|var|boot|run)/[a-zA-Z0-9_/.-]+"' "$1" \
        | tr -d '"' \
        | sort -u
}

format_list() {
    if [ -z "$1" ]; then
        echo "  *(none)*"
    else
        echo "$1" | sed 's|^|  - `|; s|$|`|'
    fi
}

# --- generate ------------------------------------------------------------
{
cat <<EOF
# Agnosys Capability Map

> Per-module kernel-surface capability — the syscalls, sys_* wrappers,
> subprocess binaries, and hard-coded filesystem paths each module can
> touch. Generated by \`scripts/gen-capability-map.sh\`; \`--check\` drives
> the staleness gate (when wired into CI).

**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ) (regenerate via \`scripts/gen-capability-map.sh\`)
**Source commit:** $(git rev-parse --short HEAD 2>/dev/null || echo "(uncommitted)")
**agnosys version:** $(cat VERSION)

## How to read this

For each module, four capability columns:

- **Syscalls**: direct \`syscall(SYS_*)\` references. The kernel syscalls the module can invoke directly.
- **\`sys_*\` wrappers**: cyrius stdlib helpers (e.g. \`sys_open\`, \`sys_read\`) — each maps to one kernel syscall.
- **Subprocess binaries**: argv-exec paths — the module spawns these as children.
- **Filesystem paths**: hard-coded \`/sys\`, \`/proc\`, \`/dev\`, \`/etc\`, \`/var\`, \`/boot\`, \`/run\` paths.

This is a coarse static scan, not a call-graph. Per-fn capability resolution requires a real cyrius AST walker and is deferred (per V1.2.2 slot scope).

## Per-profile capability rollup

Consumer-side: pulling \`dist/agnosys-<profile>.cyr\` admits the union of the included modules' capabilities below.

| Profile | Modules |
|---|---|
| **core** | syscall, error, logging |
| **security** | security, mac, audit, pam |
| **storage** | luks, dmverity, fuse |
| **trust** | tpm, ima, secureboot, certpin |
| **system** | journald, bootloader, udev, drm, netns, update |

For sandbox-policy authoring (kavach Landlock / seccomp filters, etc.): the per-module sections below give the syscall + path universe each profile expands to. Aggregate the modules in your profile to derive the full allowlist.

## Per-module detail

EOF

# Iterate modules
for ((i=0; i<${#modules[@]}; i+=2)); do
    name="${modules[i]}"
    file="${modules[i+1]}"
    [ -f "$file" ] || continue

    syscalls=$(extract_syscalls "$file" || true)
    sys_calls=$(extract_sys_calls "$file" || true)
    exec_paths=$(extract_exec_paths "$file" || true)
    fs_paths=$(extract_fs_paths "$file" || true)

    n_sc=$(echo "$syscalls" | grep -c . || true)
    n_sys=$(echo "$sys_calls" | grep -c . || true)
    n_ex=$(echo "$exec_paths" | grep -c . || true)
    n_fs=$(echo "$fs_paths" | grep -c . || true)

    cat <<EOF
### \`$name\` ($file)

| | Count |
|---|---|
| Direct syscalls | $n_sc |
| \`sys_*\` wrappers | $n_sys |
| Subprocess binaries | $n_ex |
| Filesystem paths | $n_fs |

**Direct syscalls:**

$(format_list "$syscalls")

**\`sys_*\` wrappers:**

$(format_list "$sys_calls")

**Subprocess binaries:**

$(format_list "$exec_paths")

**Filesystem paths:**

$(format_list "$fs_paths")

EOF
done

cat <<'EOF'
## Notes for downstream sandbox authors

- **Subprocess binaries** are absolute-path argv-exec only (per ADR-001). No shell, no `$PATH` lookup. Sandbox authors can `execve`-allowlist these specific paths.
- **Filesystem paths** include both prefixes (e.g. `/sys/firmware/efi`) and full paths (e.g. `/sys/firmware/efi/efivars/SecureBoot-...-93ca-...`); when authoring read-only Landlock rules, prefix-match works for the directory cases.
- **Syscalls** listed are direct — `sys_*` wrappers transitively invoke their named syscalls (`sys_open` → `openat`, `sys_read` → `read`, etc.) per cyrius stdlib `lib/syscalls*.cyr`.
- The single AGNOS-defined custom syscall is `SYS_AGNOS_AUDIT_LOG = 520` (audit module). Sandbox policies that don't need agnosys's own audit-log surface can deny 520.
- This map captures **direct** capability only. Transitive capability through the cyrius stdlib (e.g. `lib/process.cyr` exec helpers) and through other modules is not enumerated here. For exhaustive coverage, take the union across all modules in the consumer's profile bundle.

EOF
} > "$TMP"

if [ "$CHECK" -eq 1 ]; then
    # Compare structure only — strip the auto-rotating timestamp line
    # and "Source commit" SHA so identical-source-state comparisons
    # don't false-fail on rerun. Body content (per-module sections)
    # is what stale-detection actually cares about.
    norm() { sed -e '/^\*\*Generated:\*\*/d' -e '/^\*\*Source commit:\*\*/d' "$1"; }
    if ! diff -q <(norm "$TMP") <(norm "$OUT") > /dev/null 2>&1; then
        echo "ERROR: $OUT is stale. Run 'scripts/gen-capability-map.sh' and commit." >&2
        diff <(norm "$OUT") <(norm "$TMP") | head -40
        rm -f "$TMP"
        exit 1
    fi
    rm -f "$TMP"
    echo "ok: $OUT matches src/"
else
    mv "$TMP" "$OUT"
    echo "regenerated: $OUT"
fi
